### ISSUE TITLE
Admin User Story: Monitor and manage comments

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#11]
As an Admin, I want to monitor and manage comments on events so that inappropriate content can be removed.

### Acceptance Criteria

- [x] Be notified of all new comments
- [x] Delete inappropriate comments
- [x] Contact registered user to not abuse the comments and warn them of removal from a registered user

### Tasks

- [ ] Admin panel set up
