### ISSUE TITLE
Visitor User story: 

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#12]
As a user, I want to browse events without needing to register so that I can see what’s happening in my area.

### Acceptance Criteria

- [x] Events are visible to everyone
- [x] Visitors can search by categories 

### Task

- [x] Display category buttons 
- [x] Link buttons to category model
