### ISSUE TITLE
User Story: View post list paginated

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#14]
As site user I can view events in a paginated way so that i can select one that interests me. 

### Acceptance Criteria

- [x] A number of posts are listed
- [x] Events are seen on the main page and in the category pages
- [x] Events are displayed in a paginated way, Short snippets 

### Tasks

- [x] Use Django's built-in Pagination class
- [x] Create a pagination html to add to relevant pages
