### ISSUE TITLE
User Story: User Login functionality

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#16]
As a user I can log in to my account so that I can add events, comment and indicate attendance that are reserved for registered user

### Acceptance Criteria

- [x] User can log in
- [x] User can see that they are logged in
- [x] When the user is logged in they can comment and show interest of attending

### Tasks:

- [x] Login using form
- [x] Display a message or change login button to logout
