### ISSUE TITLE
All users: Open a post

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#2]
As a Site User, I can click on a events so that I can read the full text.

### Acceptance Criteria

- [x] When a event is clicked on a detailed view of the post is seen.
- [x] The event card is to display an image, date, short description and a link to page with full details

### Tasks

- [x] edit the templates accordingly to display only the relevant information
- [x] create a link to the detailed event page
