### ISSUE TITLE
User Story: Open a event post from the calendar

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#20]
As a user I can open a event listing from the calendar so that see more details of the event

### Acceptance Criteria

- [x] display a calendar view
- [x] Show event title on the relevant date in the calendar 
- [x] link the title to the events details page 

### Tasks

- [x] Use FullCalendar
- [x] Create a view and JsonResponse for getting the event and adding them to the calendar
- [x] Link entries on the calendar to the events url
- [x] helper, get_object_or_404 is added
