### ISSUE TITLE
User Story: View Calendar

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#21]
As a user I can view a calendar of events so that see when the events are on

### Acceptance Criteria

- [x] View Calendar of months
- [x] Display the current month and show event listings

### Tasks

- [x] Create a calendar using FullCalendar and bootstrap 
- [x] get events from the database and display them on the relevant days
- [x] Designed with base html and additional calendar.html for body
