### ISSUE TITLE
Admin User Story: view event request and comment requests

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#22]
As the Admin I can view event request and comment requests, so that I can review and approve them

### Acceptance Criteria

- [x] See addevent post requests
- [x] See comments in events requests
- [x] approve comments and events

### Tasks

- [x] Admin panel setup
