### ISSUE TITLE
Admin: Mark addevent request and comment requests as read

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#23]
As admin I can mark addevent and comment requests as read so that I know which ones I've seen

### Acceptance Criteria

- [x] View addevent requests
- [x] View comment requests
- [x] View who is indicated attending an event
- [x] select and mark the ones I've read
