### ISSUE TITLE
Admin User Story: Modify or delete events or comments 

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#24]
As a site admin I can modify/edit/delete a event or comment so that I can manage my website

### Acceptance Criteria

- [x] See all events and comments
- [x] Be able to select a event or comment
- [x] Delete offending comment or event that does not align with the sites principles
