### ISSUE TITLE
User Story: Organiser can see all events they've created

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#25]
As a user/event organiser I can view all the events I've created so that I can manage them.

### Acceptance Criteria

- [x] Display a template html that displays users events 
- [x] Like the events_by_category.html you'll be able to select an event
- [x] all the users created events can be seen and not just the filtered current ones

### Tasks

- [x] Add link in nav bar
- [x] views, url and html for my events
