### ISSUE TITLE
Developer: Using Agile principles

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#27]
As a developer I can use Agile principles so that I can keep on track of each stage of the plan and make changes to MoSCoW prioritisation as required.

###Acceptance Criteria

- [x] Use Agile in the development of the project
- [x] Form Epics, User stories and sprints

### Tasks

- [x] Create user stories for the project
- [x] Prioritise the user stories using MoSCoW prioritisation 
- [x] Breakdown the user stories into sprints
