### ISSUE TITLE
Developer: Design an Database Schema

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#28]
As a Developer I want to Design a database schema so that to show the relationships between models pk, fk.

### Acceptance Criteria

- [x] The database schema will contain, Events, Categories, Comments and attending
- [x] Users will be able to search by categories, events they've created, by date etc

### Tasks
- [x] Design Tables for AddEvents, Comment, Category, Attending
- [x] Create relationships between the tables
