### ISSUE TITLE
Developer: Wireframe

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#29]
As a Developer  I want to create a wireframe and prototype so that I can display the layout and design of the application.

###Acceptance Criteria

- [x] The Wireframe will display base templates components, Nav menu, footer, search bar
- [x] It will display each of individual page sections
- [x] It will have a base colour scheme and design layout
- [x] It will show the user flow and how the user will interact with the app.

### Tasks:

- [x] Collect information from the user stories to understand the design requirements
- [x] Using Figma, create a detailed and prototype level wireframe
