### ISSUE TITLE
User Story: Event Reviews and ratings

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#33]
As a user I can see ratings and review so that I can have more info on organiser or event

### Acceptance Criteria

- [ ] Reoccurring events will have review option 
- [ ] Organisers will have a review option
- [ ] Reviews are only writting by registed user
- [ ] Reviews will be in draft before the admin will publish them
