### ISSUE TITLE
User Story: 404 page

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#34]
As a user I can see the nav-bar so that I can easily go back to the home screen

### Acceptance Criteria

- [x] See nav-bar with same template design as other pages.
- [x] A 404 message will indicate that the page can't be found or no such event

### Tasks
- [x] Create a 404 page using base html template
