### ISSUE TITLE
User Story: Sign up prompt

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#35]
As a non-registered user I can register for an account so that I add events, write comments & show attendance

### Acceptance Criteria

- [x] View a register and login button
- [x] The register button will bring you to a form that asks for username, email address and password
- [x] Message to indicate successful sign up
