### ISSUE TITLE
User Story: UX design

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#36]
As a user I want to see a footer with external links so that I can see the apps social media

### Acceptance Criteria

- [x] Links to social media
- [x] footer that displays brand and social media links

### Tasks

- [x] Create a footer
- [x] Link to social media
