### ISSUE TITLE
User Story: Smooth transition in app

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#37]
As a user, I want the app to function smoothly, so I expect any remaining bugs to be fixed.

### Acceptance Criteria

- [x] All links work correctly
- [x] I will see notifications when a form is incorrectly filled

### Tasks

- [x] Test all features
- [x] Test page, buttons and forms
