### ISSUE TITLE
User Story: UI/UX Enhancements

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#38]
As a user, I expect any UI issues to be resolved to improve my experience.

### Acceptance Criteria

- [x] buttons are in the right place
- [x] text is easy to read
- [x] The app links are available by screen readers.

### Tasks

- [x] HTML clean up
- [x] add aria labels
