### ISSUE TITLE
Admin User Story: SEO optimisation 

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#39]
As an admin, I want the site to achieve a high score in Google Chrome Lighthouse (Performance, Accessibility, SEO, and Best Practices) to ensure optimal user experience and technical quality.

### Acceptance Criteria

- [x] Lighthouse highest possible score
- [x] SEO

### Tasks

- [x] Work with Google Chrome Lighthouse to see where the website can be optimised
- [x] Resize images, add external links and add meta data to title
- [x] aria label
