### ISSUE TITLE
New User: Account registration

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#4]
As a Site User I can register an account so that I can become a registered user and comment/like a post.

### Acceptance Criteria

- [x] After given details a user can register an account. Username, email, password.
- [x] Indication to the user if any of the form fields are invalid 
- [x] Message displayed to user

### Tasks
- [x] Create a signup page in view and template
- [x] Create a signup form from bootstrap
