### ISSUE TITLE
Admin User Story: Review site before launch

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#40]
As an admin I want to see the finished site before launch so that I can make any necessary changes  

### Acceptance Criteria

- [x] Fully functional site
- [x] No bugs
- [x] The site meets or exceeds expectation

### Tasks

- [x] Create a readme for the user
- [x] Display the site and show steps taken
- [x] Identify future features to the client so they see the app's potential to grow
