### ISSUE TITLE
Admin User Story: Approve registered users events

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#5]
As an Admin, I want to approve or reject registered users publishing events so that only verified events are added to the app.

### Acceptance Criteria

- [x] The Admin should be able to view a list of pending event requests from registered users / organisers.
- [x] The Admin should be able to approve or reject each event individually.
- [x] Upon approval, the event will be published

### Tasks
 - [x] Only allow authorised users to get access to add an event  form
 - [x] non registered users will be requested to login or register
 - [x] Events are marked as draft until admin changes status to published
