### ISSUE TITLE
User Story: Create Event

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#6]
As a register user I can create an event so that I can inform people about upcoming performances.

### Acceptance Criteria

- [x] Post information on event, date/time, location, picture and description
- [x] Edit or delete created post
- [x] Confirmation on event created 

### Tasks:

- [x] Create a model for events. To include: Title, image, description,  category, start date, end date, location, price, link to event page, comment
- [x] Create a form with this model criteria for the user to fill in.
- [x] Display this form with templates and views
- [x] Display message to confirm event has been created
- [x] link uploaded image to event blog with Cloudinary
