### ISSUE TITLE
Registered User: Search for events by category 

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#7]
As a User, I want to browse and search for events so that I can find events that interest me.

### Acceptance Criteria

- [x] User can use filters to search for events by category
- [x] User can view event details including description, location, and schedule

### Tasks
- [x] Allow filter by category
- [x] Set up relationship between AddEvent and Category models
