### ISSUE TITLE
Register User story: indicate attendance

### ISSUE THREAD

**Issue by Andrewodwyer** [Andrewodwyer/City-Events-Blog#9]
As a Registered User, I want to indicate my attendance to events so that others know I’m planning to go.

### Acceptance Criteria

- [x] Button below post that indicates that the register user is attending. button that turns to a green tick
- [x] An option to undo this.

### Task

- [x] view for attending model
- [x] addevent_detail html DTL
